[general]
enabled = yes
webenabled = yes
port = 5038
bindaddr = 127.0.0.1


[admin]
secret = t3sl@admin
timestampevents = yes
displayconnects = yes
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,agent,reporting,command,user
write = system,call,agent,reporting,command,user

[amiws]
secret = t3sl@admin
timestampevents = yes
displayconnects = yes
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.255
read = system,call,agent,reporting,user
write = system,call,agent,reporting,user

[ajam]
secret = t3sl@admin
deny = 0.0.0.0/0.0.0.0
;permit = 127.0.0.1/255.255.255.0
permit = 172.40.1.0/255.255.255.0
permit = 192.168.88.0/255.255.255.0
permit = 172.16.16.0/255.255.255.0
read = system,agent,reporting
write = system,agent,reporting


[ajamuser]
secret = t3sl@admin
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.0
permit = 192.168.110.0/255.255.255.0
read = system,call,agent,reporting,user
write = system,agent,reporting

[aiservice]
secret = 3pStE!n*F1l3s_88
deny = 0.0.0.0/0.0.0.0
permit = 127.0.0.1/255.255.255.0
permit = 192.168.110.0/255.255.255.0
read = system,call,agent,reporting,user
write = system,agent,reporting
